#!/bin/bash
BACKUP_DIR="/var/lib/mysql/backup"
/bin/mysqldump -u slurm_backup -p<%= @db_pass -%> slurm_acct_db > $BACKUP_DIR/$HOSTNAME_$(date +%Y%m%d).sql; /usr/bin/gzip $BACKUP_DIR/$HOSTNAME_$(date +%Y%m%d).sql