---
- name: Install Munge Dependencies
  yum:
    name: "{{ munge_packages }}"
    state: present

- name: Add Munge Group
  group:
    name: munge
    gid: 1002
    state: present

- name: Add Munge User
  user:
    name: munge
    home: /var/run/munge
    group: munge
    shell: /bin/false
    uid: 503
    state: present

- name: Setup base Munge directory
  file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: 0700

- name: Setup /var Munge directories
  file:
    path: "{{ item }}"
    state: directory
    owner: munge
    group: munge
    recurse: yes
  loop:
    - /var/lib/munge
    - /var/log/munge

- name: Copy munge key
  copy:
    src: munge.key_blank
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400

- name: Ensure Munge is started & runs @ boot
  service:
    name: munge
    state: started
    enabled: yes
  when: not ansible_check_mode